### PR TITLE
Extract date from filename

### PR DESCRIPTION
**Pull request by rdenadai**
If date is empty from `frontmatter` we enter in a way to grab the alternative date and slug.
The slug itself is always returned from the `get_slug`, so this is a deviation in case the date is empty.

- Closes
    - #23 

Example: `2025-05-01-another-blog-post.md`
image

image

### CODE REVIEW

**Review by rochacbruno — CHANGES_REQUESTED** [review]
There is a problem:

Create a new file `content/2024-01-01-new-post.md`
```markdown
---
slug: this-is-the-slug-i-want
---
# post content...
```

Then what happens is that the page `new-post.html` is generated 

Expected `this-is-the-slug-i-want.html`

The frontmatter must take precedence not only for date but also for slug.

**Comment by rochacbruno** [comment]
Maybe, the implementation must go on `get_slug` and `get_date` functions, passing the `path` to those 2 functions.

**Comment by rochacbruno** [comment]
For example 

https://github.com/rochacbruno/marmite/blob/fab7673841e207797600bf166a4bb9d7e323ffc6/src/main.rs#L257 

At this line, instead of just returning None for date, you can call your `get)alternative_date_from_slug` OR return None

Then same on the get_slug function, the lines

https://github.com/rochacbruno/marmite/blob/fab7673841e207797600bf166a4bb9d7e323ffc6/src/main.rs#L267-L270

must return the filename with the date part (if exists) stripped out.

**Comment by rdenadai** [comment]
Ah!! of course ... I'll work to fix this!

Thanks!!

**Comment by rdenadai** [comment]
Hey @rochacbruno did one of the suggested changes ... please let me know if anything else needs more tweaks!

Thanks!!!

**Review by rochacbruno — APPROVED** [review]

**Pull request merged**
